### ISSUE TITLE
If the server takes more than 10 seconds to load the subworld... it breaks.

### ISSUE THREAD

**Issue by Murkeee** [jjohnsnaill/SubworldLibrary#10]
Tried to access a subworld through the mod "The Stars Above" on a dedicated server. It works but seemingly only if the server takes less than about 10 seconds to load the second server instance otherwise it spits out some errors and soft-bricks my game. The second server instance gets stuck on "Adding Recipes..." 

while the original server instance displays:
"Server hung for more than 10 seconds. Cannot determine cause from watchdog thread. The operation has timed out." but remains operational (As in the server doesn't crash and the player can still do stuff if they restart their game after the soft-brick and rejoins).

How to reproduce:
1. Enable large mods such as Calamity, Thorium, Fargos, anything that makes the game take longer to load.
2. Enable The Stars Above
3. Load up tmodloader server
4. load into server and attempt to go to a subworld.
5. Watch it not work.
6. Disable all large content mods and try again.
7. Watch it work.

I have attached the server.log file.
[server.log](https://github.com/jjohnsnaill/SubworldLibrary/files/10327374/server.log)

**Comment by jjohnsnaill** [comment]
This was a poor attempt to prevent the main server from hanging if a subserver did, will be fixed in the next update.

**Comment by Murkeee** [comment]
> This was a poor attempt to prevent the main server from hanging if a subserver did, will be fixed in the next update.

Right... I thought this might be the case. Is there an ETA on this next update? In excited for subworld to be functional in multiplayer.

**Comment by Konin-Sensei** [comment]
I get the same logged error but a somewhat different result (running Calamity & Stars Above). If I go to a Stars Above subworld, the 'Server hung' error will appear but I'll load into the subworld. Upon returning to the main world, it will remove the underworld and beaches and crunch the map down to the size of the subworld. Almost like the properties of the subworld are being imposed on the main world. Manually closing the command prompt window for the subworld server and logging out & rejoining the game fixes the main world. It does also appear that the subworlds are not saving but I'm assuming that's because they aren't being exited properly.

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.0.1.
